version: "3.5"
services:
  nats:
    image: nats
    command: "-cluster nats://0.0.0.0:6222 --cluster_name ch-nats-cluster"
    ports:
      - "8222:8222"
      - "4200:4222"
    networks: ["nats"]
  nats-1:
    image: nats
    command: "-cluster nats://0.0.0.0:6201 -routes=nats://nats:6222 --cluster_name ch-nats-cluster"
    ports:
      - "4201:4222"
    networks: ["nats"]
    depends_on: ["nats"]
  nats-2:
    image: nats
    command: "-cluster nats://0.0.0.0:6202 -routes=nats://nats:6222 --cluster_name ch-nats-cluster"
    ports:
      - "4202:4222"
    networks: ["nats"]
    depends_on: ["nats"]

networks:
  nats:
    name: nats

# clustering docs: https://docs.nats.io/nats-server/configuration/clustering
